# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/grpc_control/squad_control.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'src/grpc_control/squad_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$src/grpc_control/squad_control.proto\x12\x0cgrpc_control\"\x12\n\x10GetStatusRequest\"X\n\x11GetStatusResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"2\n\x11RunCommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"I\n\x12RunCommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x16\n\x14GetActiveModeRequest\"%\n\x15GetActiveModeResponse\x12\x0c\n\x04mode\x18\x01 \x01(\t\"!\n\x11SwitchModeRequest\x12\x0c\n\x04mode\x18\x01 \x01(\t\"6\n\x12SwitchModeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdf\x02\n\x13SquadControlService\x12L\n\tGetStatus\x12\x1e.grpc_control.GetStatusRequest\x1a\x1f.grpc_control.GetStatusResponse\x12O\n\nRunCommand\x12\x1f.grpc_control.RunCommandRequest\x1a .grpc_control.RunCommandResponse\x12X\n\rGetActiveMode\x12\".grpc_control.GetActiveModeRequest\x1a#.grpc_control.GetActiveModeResponse\x12O\n\nSwitchMode\x12\x1f.grpc_control.SwitchModeRequest\x1a .grpc_control.SwitchModeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc_control.squad_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATUSREQUEST']._serialized_start=54
  _globals['_GETSTATUSREQUEST']._serialized_end=72
  _globals['_GETSTATUSRESPONSE']._serialized_start=74
  _globals['_GETSTATUSRESPONSE']._serialized_end=162
  _globals['_RUNCOMMANDREQUEST']._serialized_start=164
  _globals['_RUNCOMMANDREQUEST']._serialized_end=214
  _globals['_RUNCOMMANDRESPONSE']._serialized_start=216
  _globals['_RUNCOMMANDRESPONSE']._serialized_end=289
  _globals['_GETACTIVEMODEREQUEST']._serialized_start=291
  _globals['_GETACTIVEMODEREQUEST']._serialized_end=313
  _globals['_GETACTIVEMODERESPONSE']._serialized_start=315
  _globals['_GETACTIVEMODERESPONSE']._serialized_end=352
  _globals['_SWITCHMODEREQUEST']._serialized_start=354
  _globals['_SWITCHMODEREQUEST']._serialized_end=387
  _globals['_SWITCHMODERESPONSE']._serialized_start=389
  _globals['_SWITCHMODERESPONSE']._serialized_end=443
  _globals['_SQUADCONTROLSERVICE']._serialized_start=446
  _globals['_SQUADCONTROLSERVICE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
