# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_control import squad_control_pb2 as src_dot_grpc__control_dot_squad__control__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/grpc_control/squad_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SquadControlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/grpc_control.SquadControlService/GetStatus',
                request_serializer=src_dot_grpc__control_dot_squad__control__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=src_dot_grpc__control_dot_squad__control__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.RunCommand = channel.unary_unary(
                '/grpc_control.SquadControlService/RunCommand',
                request_serializer=src_dot_grpc__control_dot_squad__control__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=src_dot_grpc__control_dot_squad__control__pb2.RunCommandResponse.FromString,
                _registered_method=True)
        self.GetActiveMode = channel.unary_unary(
                '/grpc_control.SquadControlService/GetActiveMode',
                request_serializer=src_dot_grpc__control_dot_squad__control__pb2.GetActiveModeRequest.SerializeToString,
                response_deserializer=src_dot_grpc__control_dot_squad__control__pb2.GetActiveModeResponse.FromString,
                _registered_method=True)
        self.SwitchMode = channel.unary_unary(
                '/grpc_control.SquadControlService/SwitchMode',
                request_serializer=src_dot_grpc__control_dot_squad__control__pb2.SwitchModeRequest.SerializeToString,
                response_deserializer=src_dot_grpc__control_dot_squad__control__pb2.SwitchModeResponse.FromString,
                _registered_method=True)


class SquadControlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SquadControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=src_dot_grpc__control_dot_squad__control__pb2.GetStatusRequest.FromString,
                    response_serializer=src_dot_grpc__control_dot_squad__control__pb2.GetStatusResponse.SerializeToString,
            ),
            'RunCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCommand,
                    request_deserializer=src_dot_grpc__control_dot_squad__control__pb2.RunCommandRequest.FromString,
                    response_serializer=src_dot_grpc__control_dot_squad__control__pb2.RunCommandResponse.SerializeToString,
            ),
            'GetActiveMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveMode,
                    request_deserializer=src_dot_grpc__control_dot_squad__control__pb2.GetActiveModeRequest.FromString,
                    response_serializer=src_dot_grpc__control_dot_squad__control__pb2.GetActiveModeResponse.SerializeToString,
            ),
            'SwitchMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchMode,
                    request_deserializer=src_dot_grpc__control_dot_squad__control__pb2.SwitchModeRequest.FromString,
                    response_serializer=src_dot_grpc__control_dot_squad__control__pb2.SwitchModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_control.SquadControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_control.SquadControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SquadControlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_control.SquadControlService/GetStatus',
            src_dot_grpc__control_dot_squad__control__pb2.GetStatusRequest.SerializeToString,
            src_dot_grpc__control_dot_squad__control__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_control.SquadControlService/RunCommand',
            src_dot_grpc__control_dot_squad__control__pb2.RunCommandRequest.SerializeToString,
            src_dot_grpc__control_dot_squad__control__pb2.RunCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_control.SquadControlService/GetActiveMode',
            src_dot_grpc__control_dot_squad__control__pb2.GetActiveModeRequest.SerializeToString,
            src_dot_grpc__control_dot_squad__control__pb2.GetActiveModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_control.SquadControlService/SwitchMode',
            src_dot_grpc__control_dot_squad__control__pb2.SwitchModeRequest.SerializeToString,
            src_dot_grpc__control_dot_squad__control__pb2.SwitchModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
